// this is a port of
// https://github.com/edanaher/twidlk/blob/master/src/Main.hs
// mostly generated by Claude 3.5 Sonnet (but bugs fixed by me)

// licensed under GPLv3

use std::env;
use std::error::Error;

use twidlk_rust::twiddler_config::{txt_to_cfg, cfg_to_txt};

fn main() -> Result<(), Box<dyn Error>> {
    let args: Vec<String> = env::args().collect();
    let filename = match args.get(1) {
        Some(f) => f,
        None => return Err("No filename provided".into()),
    };

    let input_is_text = filename.ends_with(".txt");

    if input_is_text {
        txt_to_cfg(&filename)?;
    } else {
        cfg_to_txt(&filename)?;
    }
    Ok(())
}
