// this is a port of
// https://github.com/edanaher/twidlk/blob/master/src/Main.hs
// mostly generated by Claude 3.5 Sonnet (but bugs fixed by me)

// licensed under GPLv3

use std::env;

use twidlk_rust::twiddler_config::{txt_to_cfg, cfg_to_txt};

fn main() -> std::io::Result<()> {
    let args: Vec<String> = env::args().collect();
    let filename = match args.get(1) {
        Some(f) => f,
        None => return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, "Requires a filename as argument")),
    };

    let input_is_text = filename.ends_with(".txt");

    if input_is_text {
        match txt_to_cfg(filename) {
            Ok(_) => {},
            Err(e) => return Err(e),
        }
    } else {
        match cfg_to_txt(filename) {
            Ok(_) => {},
            Err(e) => return Err(e),
        }
    }
    Ok(())
}
